import "./ReportsActions.css";
import { useState } from "react";

function ReportsActions({ onSearch , openModal  }: any) {

    const [value, setValue] = useState("");

    const handleChange = (e: any) => {
        const val = e.target.value;
        setValue(val);
        onSearch(val); 
    };

    return (
        <div className="reports-actions">

            <input
                type="text"
                placeholder="Search by report name, type, or generated by..."
                value={value}
                onChange={handleChange}
            />

            <button onClick={openModal} className="add-report-btn">
        + Add Report
      </button>

        </div>
    );

}

export default ReportsActions;